region='REGION_NAME'
username='admin'
password='SERVICEPW'
project_name='admin'
project_domain_id=None
user_domain_id=None
auth_url='http://iam.savitestbed.ca:5000/v2.0/'
janus_address='CTRL_IP'
janus_port=8091
rabbit_user = 'guest'
rabbit_password = 'RABBITPW'
rabbit_host = 'CTRL_IP'
